name: 'Profile Readme Development Stats'
author: Anmol Pratap Singh
description: 'Are you an early 🐤 or a night 🦉? When are you most productive during the day? Let''s check out in your readme!'

inputs:
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    required: true
    default: ${{ github.token }}

  WAKATIME_API_KEY:
    description: 'Your Wakatime API Key'
    required: true

  SECTION_NAME:
    description: 'Name used in readme to scope the updated section'
    required: false
    default: "waka"

  PULL_BRANCH_NAME:
    required: false
    description: "The branch to get the readme from"
    default: ""

  PUSH_BRANCH_NAME:
    required: false
    description: "The branch to update the readme in"
    default: ""

  SHOW_OS:
    required: false
    description: 'Show the list of OS Worked on In dev metrics'
    default: "True"

  SHOW_PROJECTS:
    required: false
    description: 'Show the list of projects worked on in dev metrics'
    default: "True"

  SHOW_EDITORS:
    required: false
    description: 'Show the Editors used in dev metrics'
    default: "True"

  SHOW_TIMEZONE:
    required: false
    description: 'Show the time zone in the dev metrics'
    default: "True"

  SHOW_COMMIT:
    required: false
    description: "Shows the number of commit graph in the dev metrics"
    default: "True"

  SHOW_LANGUAGE:
    required: false
    description: "Show the Coding language used in dev metrics"
    default: "True"

  SHOW_LINES_OF_CODE:
    required: false
    description: "Show the Total Lines of code written Badge till date"
    default: "False"

  SHOW_LANGUAGE_PER_REPO:
    required: false
    description: "Show language or framework used across different repository"
    default: "True"

  SHOW_LOC_CHART:
    required: false
    description: ""
    default: "True"

  SHOW_DAYS_OF_WEEK:
    required: false
    description: "show day of week you are most productive"
    default: "True"

  SHOW_PROFILE_VIEWS:
    required: false
    description: "Shows the current profile views"
    default: "True"

  SHOW_SHORT_INFO:
    required: false
    description: "Shows the short facts"
    default: "True"

  SHOW_UPDATED_DATE:
    required: false
    description: "Show updated date"
    default: "True"

  SHOW_TOTAL_CODE_TIME:
    required: false
    description: "Show Total Time you have coded"
    default: "True"

  COMMIT_BY_ME:
    required: false
    description: "Git commit with your own name and email"
    default: "False"
  
  COMMIT_MESSAGE:
    required: false
    description: "Git commit message"
    default: "Updated with Dev Metrics"

  COMMIT_USERNAME:
    required: false
    description: "Git commit custom username"
    default: ""
  
  COMMIT_EMAIL:
    required: false
    description: "Git commit custom email"
    default: ""

  COMMIT_SINGLE:
    required: false
    description: "Erase commit history on each commit"
    default: "False"

  LOCALE:
    required: false
    description: "Show stats in your own language"
    default: "en"

  UPDATED_DATE_FORMAT:
    required: false
    description: "Updated date format"
    default: "%d/%m/%Y %H:%M:%S"

  IGNORED_REPOS:
    required: false
    description: "Repos you don't want to be counted"
    default: ""

  SYMBOL_VERSION:
    required: false
    description: "Version of the symbol block and empty of the progress bar"
    default: "1"

  SYMBOL_STYLE:
    required: false
    description: "Style of the symbol block and empty of the progress bar"
    default: ""

  CODE_BLOCK_LANGUAGE:
    required: false
    description: "Language of the code block"
    default: "text"

  DEBUG_LOGGING:
    required: false
    description: "Whether to enable action debug logging"
    default: ${{ runner.debug }}

runs:
  using: 'ubuntu-latest'
  steps:
    - uses: actions/checkout@v2
    - uses: anmol098/waka-readme-stats@master
      with:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        SECTION_NAME: ${{ inputs.SECTION_NAME }}
        PULL_BRANCH_NAME: ${{ inputs.PULL_BRANCH_NAME }}
        PUSH_BRANCH_NAME: ${{ inputs.PUSH_BRANCH_NAME }}
        SHOW_OS: ${{ inputs.SHOW_OS }}
        SHOW_PROJECTS: ${{ inputs.SHOW_PROJECTS }}
        SHOW_EDITORS: ${{ inputs.SHOW_EDITORS }}
        SHOW_TIMEZONE: ${{ inputs.SHOW_TIMEZONE }}
        SHOW_COMMIT: ${{ inputs.SHOW_COMMIT }}
        SHOW_LANGUAGE: ${{ inputs.SHOW_LANGUAGE }}
        SHOW_LINES_OF_CODE: ${{ inputs.SHOW_LINES_OF_CODE }}
        SHOW_LANGUAGE_PER_REPO: ${{ inputs.SHOW_LANGUAGE_PER_REPO }}
        SHOW_LOC_CHART: ${{ inputs.SHOW_LOC_CHART }}
        SHOW_DAYS_OF_WEEK: ${{ inputs.SHOW_DAYS_OF_WEEK }}
        SHOW_PROFILE_VIEWS: ${{ inputs.SHOW_PROFILE_VIEWS }}
        SHOW_SHORT_INFO: ${{ inputs.SHOW_SHORT_INFO }}
        SHOW_UPDATED_DATE: ${{ inputs.SHOW_UPDATED_DATE }}
        SHOW_TOTAL_CODE_TIME: ${{ inputs.SHOW_TOTAL_CODE_TIME }}
        COMMIT_BY_ME: ${{ inputs.COMMIT_BY_ME }}
        COMMIT_MESSAGE: ${{ inputs.COMMIT_MESSAGE }}
        COMMIT_USERNAME: ${{ inputs.COMMIT_USERNAME }}
        COMMIT_EMAIL: ${{ inputs.COMMIT_EMAIL }}
        COMMIT_SINGLE: ${{ inputs.COMMIT_SINGLE }}
        LOCALE: ${{ inputs.LOCALE }}
        UPDATED_DATE_FORMAT: ${{ inputs.UPDATED_DATE_FORMAT }}
        IGNORED_REPOS: ${{ inputs.IGNORED_REPOS }}
        SYMBOL_VERSION: ${{ inputs.SYMBOL_VERSION }}
        SYMBOL_STYLE: ${{ inputs.SYMBOL_STYLE }}
        CODE_BLOCK_LANGUAGE: ${{ inputs.CODE_BLOCK_LANGUAGE }}
        DEBUG_LOGGING: ${{ inputs.DEBUG_LOGGING }}

# runs:
#   using: 'docker'
#   image: 'docker://wakareadmestats/waka-readme-stats:master'

branding:
  icon: 'activity'
  color: 'orange'
